### ISSUE TITLE
Fixing the Manage Subscriptions render list problem

### ISSUE THREAD

**Issue by wahudamon** [evilfactorylabs/nadya#33]
Fix the render list problem. The problem is on manage subscriptions page that always show RpNaN at the first list.

**Comment by faultables** [comment]
Update:

Sepertinya RpNaN muncul disebabkan sebelumnya data untuk "Subscriptions" dan "User" masih di satu _database_. Dan semenjak PR #30 sudah dipisah.

Jadi maksudnya step to reproduce yang aku jelaskan di Discord sepertinya sudah outdated. Mungkin bila memiliki cara untuk produce lain, issue ini masih berlaku ya.

Thanks and sorry
