### ISSUE TITLE
Feedback v1.0.0-canary.1

### ISSUE THREAD

**Issue by faultables** [evilfactorylabs/nadya#41]
## Bug/Need enhancement

- [x] Total bundle size **~2.61MB!** (app)
- [x] Navbar si tombol Back nya ngilang. Inilah pentingnya test (app)
- [x] Navbar title ngilang! Inilah pentingnya test. (app)
- [x] Belum buat snapshot (app)
- [x] Theme color masih `#000` (app)
- [x] Logo (di Appbar) terlalu besar (app)
- [x] add `sw.js` to routes (app)
- [x] `NADYA_APP_VER` build environment masih gak jalan. Related with Zeit Now (infra)
- [x] deploy ke `canary` tapi ke deploy ke `app` juga, still investigate. (infra)

## Feature

- [x] Show (actual) notification (app)
- [x] Integrate with codecov.io (infra)
- [x] Option to delete local data (app)

**Comment by faultables** [comment]
Blocking #40

**Comment by r17x** [comment]
@108kb  Logo , maybe we can use this script https://github.com/ri7nz/Medicine/blob/master/buildlogo.js

**Comment by faultables** [comment]
my mean the logo dimension, not the size itself. but will trying it out, thanks.
