### ISSUE TITLE
design database

### ISSUE THREAD

**Issue by faultables** [evilfactorylabs/nadya#5]

**Comment by faultables** [comment]
Because PouchDB is document-based database, let me show you the high-level view of our database as an object:

```javascript
{
  user: {
    _id: String<uuid>,
    name?: String
  },
  subscriptions: [
    {
      _id: String<uuid>,
      title: String,
      cost: Number,
      subscribed_at: Number<epoch>,
      created_at: Number<epoch>,
      updated_at: Number<epoch>,
      period?: Number<Period>,
      color?: String<hex>
    }
  ]
}

enum Period {
  1 = "monthly"
  2 = "annual"
}
```

**Comment by faultables** [comment]
example:

user

```javascript
userDB.put({
  _id: generateUuid(),
  name: null
})
```

subscription

```javascript
db.put({
  _id: generateUuid(),
  title: 'Spotify',
  cost: 50000,
  subscribed_at: 1538931600000, // 10/08/2018, .getTime()
  created_at: Date.now(),
  updated_at: null, // no type-checking in js!
  period: 0,
  color: '#666' // taken from `data.json`
})
```

detail

```javascript
db.get('915f293d-a824-4f6d-801e-22a56a5c354d').then(doc => console.log(doc))
```

**Comment by faultables** [comment]
generate uuid

```javascript
(((a,b)=>{for(b=a='';a++<36;b+=a*51&52?(a^15?8^Math.random()*(a^20?16:4):4).toString(16):'-');return b})())
```

**Comment by 108kb** [comment]
@evilfactorylabs/nadya how do you think guys? Are there any missing `field` in [current](https://github.com/evilfactorylabs/nadya/issues/5#issuecomment-502628565) _schema_? Or are there any mistake here for naming a _field_?

**Comment by 108kb** [comment]
@evilfactorylabs/nadya what do you think guys? Are there any missing `field` in [current](https://github.com/evilfactorylabs/nadya/issues/5#issuecomment-502628565) _schema_? Or are there any mistake here for naming a _field_?

**Comment by faultables** [comment]
@evilfactorylabs/nadya what do you think guys? Are there any missing `field` in [current](https://github.com/evilfactorylabs/nadya/issues/5#issuecomment-502628565) _schema_? Or are there any mistake here for naming a _field_?
